version: "3"
services:
  back:
    container_name: backend
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: 'GMT'
      PGTZ: 'GMT'
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/posgresql/data

volumes:
  postgres:
