import { IMessageState } from '../../whatsapp/states/message-state.interface';
import { FirstTicketConfirmationState } from '../states/first-ticket-confirmation-state';
import { OwnerTypeInputState } from '../states/owner-type-input-state';

export enum TicketState {
  NONE = 'NONE',
  CLOSED = 'CLOSED',
  FIRST_TICKET = 'FIRST_TICKET',
  SELECT_TICKET = 'SELECT_TICKET',
  WAITING_OWNER_TYPE = 'WAITING_OWNER_TYPE',
  WAITING_COUNTERPART_NAME = 'WAITING_COUNTERPART_NAME',
  WAITING_COUNTERPART_NAME_CONFIRMATION = 'WAITING_COUNTERPART_NAME_CONFIRMATION',
  WAITING_COUNTERPART_TAXPAYER_NUMBER = 'WAITING_COUNTERPART_TAXPAYER_NUMBER',
  WAITING_COUNTERPART_TAXPAYER_NUMBER_CONFIRMATION = 'WAITING_COUNTERPART_TAXPAYER_NUMBER_CONFIRMATION',
  WAITING_COUNTERPART_PHONE = 'WAITING_COUNTERPART_PHONE',
  WAITING_COUNTERPART_PHONE_CONFIRMATION = 'WAITING_COUNTERPART_PHONE_CONFIRMATION',
  WAITING_COUNTERPART_EMAIL = 'WAITING_COUNTERPART_EMAIL',
  WAITING_COUNTERPART_EMAIL_CONFIRMATION = 'WAITING_COUNTERPART_EMAIL_CONFIRMATION',
  WAITING_COUNTERPART_ADDRESS = 'WAITING_COUNTERPART_ADDRESS',
  WAITING_COUNTERPART_ADDRESS_CONFIRMATION = 'WAITING_COUNTERPART_ADDRESS_CONFIRMATION',
}

export const getTicketStateProcessor: Record<TicketState, IMessageState> = {
  [TicketState.NONE]: null,
  [TicketState.FIRST_TICKET]: new FirstTicketConfirmationState(),
  [TicketState.SELECT_TICKET]: null,
  [TicketState.WAITING_OWNER_TYPE]: new OwnerTypeInputState(),
  [TicketState.WAITING_COUNTERPART_NAME]: null,
  [TicketState.WAITING_COUNTERPART_NAME_CONFIRMATION]: null,
  [TicketState.WAITING_COUNTERPART_PHONE]: null,
  [TicketState.WAITING_COUNTERPART_PHONE_CONFIRMATION]: null,
  [TicketState.WAITING_COUNTERPART_EMAIL]: null,
  [TicketState.WAITING_COUNTERPART_EMAIL_CONFIRMATION]: null,
  [TicketState.WAITING_COUNTERPART_ADDRESS]: null,
  [TicketState.WAITING_COUNTERPART_ADDRESS_CONFIRMATION]: null,
  [TicketState.WAITING_COUNTERPART_TAXPAYER_NUMBER]: null,
  [TicketState.WAITING_COUNTERPART_TAXPAYER_NUMBER_CONFIRMATION]: null,
  [TicketState.CLOSED]: null,
};
