export const prefix = {
  DATA_PRIVACY: 'data-privacy',
  USER_FULL_NAME: 'user-full-name',
  USER_TAXPAYER_NUMBER: 'user-taxpayer-number',
  USER_PHONE_NUMBER: 'user-phone-number',
  USER_ADDRESS: 'user-address',
  USER_EMAIL: 'user-email',
  FIRST_TICKET: 'first-contract-confirmation',
  TICKET_OWNER_TYPE: 'owner-type',
  COUNTERPART_NAME: 'counterpart-name',
  COUNTERPART_TAXPAYER_NUMBER: 'counterpart-taxpayer-number',
  COUNTERPART_PHONE_NUMBER: 'counterpart-phone-number',
  COUNTERPART_EMAIL: 'counterpart-email',
  COUNTERPART_ADDRESS: 'counterpart-address',
  SERVICE_ADDRESS: 'service-address',
  SERVICE_DETAILS: 'service-details',
  SERVICE_STEPS: 'service-details-steps',
  SERVICE_START_DATE: 'start-date',
  SERVICE_END_DATE: 'end-date',
  SERVICE_PAYMENT_AMOUNT: 'payment-amount',
  SERVICE_PAYMENT_DATES: 'payment-dates',
  SERVICE_MATERIAL_DATE: 'material-date',
  SERVICE_MATERIAL_HOW_BUY: 'material-how-buy',
  SERVICE_MATERIAL_HOW_MUCH_BUDGETS: 'material-how-much-budgets',
  SERVICE_MATERIAL_WHERE: 'material-where',
  SERVICE_MATERIAL_PAYBACK: 'material-payback',
  SERVICE_CONTRACT_CANCEL: 'contract-cancel',
  SERVICE_CONTRACT_CANCEL_DETAILS: 'contract-cancel-details',
  SERVICE_MATERIAL_HOW_MUCH: 'material-how-much',
  SERVICE_HOURS: 'service-hours',
  SERVICE_STEPS_DESCRIPTION: 'steps-description',
  SERVICE_HOURS_DESCRIPTION: 'hours-description',
  SERVICE_PAYMENT_METHOD: 'payment-method',
  SERVICE_PAYMENT_IN_CASH_METHOD: 'payment-in-cash',
  SERVICE_PAYMENT_IN_INSTALLMENTS_METHOD: 'payment-in-installments',
  SERVICE_PAYMENT_OTHER_METHOD: 'payment-other',
  SERVICE_PAYMENT_INSTALLMENT_COUNT: 'payment-installment-amount',
  SERVICE_PAYMENT_IN_INSTALLMENT_OTHER_METHOD: 'payment-in-installment-other',
  SERVICE_PAYMENT_IN_CASH_OTHER_METHOD: 'payment-in-cash-other',
  MATERIAL_IS_PART_OF_CONTRACT: 'material-is-part-of-contract',
  MATERIAL_WHO_WILL_BUY: 'material-who-buy',
  SERVICE_MATERIAL_PRE_DETERMINED_VALUE: 'material-pre-determined-value',
  MATERIAL_WHO_WILL_PAY: 'material-who-pay',
  MATERIAL_DETAILS: 'material-details',
  MATERIAL_DETAILS_DESCRIPTION: 'material-details-description',
  CONTRACT_HAS_MORE: 'contract-has-more',
  CONTRACT_HAS_MORE_DESCRIPTION: 'contract-has-more-description',
  CONTRACT_HAS_DEADLINE_MORE: 'contract-has-deadline-more',
  CONTRACT_HAS_DEADLINE_MORE_DESCRIPTION:
    'contract-has-deadline-more-description',
  SERVICE_DELIVERY_DESCRIPTION: 'service-delivery-description',
  CONTRACT_HAS_CANCELLATION_MORE: 'contract-has-cancellation-more',
  CONTRACT_HAS_CANCELLATION_MORE_DESCRIPTION:
    'contract-has-cancellation-more-description',
  WHAT_IS_CONTRACT_CANCELLATION: 'what-is-contract-cancellation',
  SERVICE_WARRANTY: 'service-warranty',
  WARRANTY_DESCRIPTION: 'warranty-description',
  JUDICIAL_RESOLUTION: 'judicial-resolution',
  CONTRACT_APPROVAL: 'contract-approval',
  CONTRACT_COUNTERPART_SIGNATURE: 'contract-counterpart-signature',
  CONTRACT_HAS_REJECTED_BY_COUNTERPART_DESCRIPTION:
    'contract-has-rejected-by-counterpart-description',
  CONTRACT_CORRECTION_BY_OWNER_DESCRIPTION: 'contract-correction-by-owner-description',
};
