export const prefix = {
  DATA_PRIVACY: 'data-privacy',
  USER_FULL_NAME: 'user-full-name',
  USER_TAXPAYER_NUMBER: 'user-taxpayer-number',
  USER_PHONE_NUMBER: 'user-phone-number',
  USER_ADDRESS: 'user-address',
  USER_EMAIL: 'user-email',
  FIRST_TICKET: 'first-contract-confirmation',
  TICKET_OWNER_TYPE: 'owner-type',
  COUNTERPART_NAME: 'counterpart-name',
  COUNTERPART_TAXPAYER_NUMBER: 'counterpart-taxpayer-number',
  COUNTERPART_PHONE_NUMBER: 'counterpart-phone-number',
  COUNTERPART_EMAIL: 'counterpart-email',
  COUNTERPART_ADDRESS: 'counterpart-address',
  SERVICE_ADDRESS: 'service-address',
  SERVICE_DETAILS: 'service-details',
  SERVICE_STEPS: 'service-details-steps',
  SERVICE_START_DATE: 'service-start-date',
  SERVICE_END_DATE: 'service-end-date',
  SERVICE_PAYMENT_AMOUNT: 'service-payment-amount',
  SERVICE_PAYMENT_DATES: 'service-payment-dates',
  SERVICE_MATERIAL_DATE: 'service-material-date',
  SERVICE_MATERIAL_HOW_BUY: 'service-material-how-buy',
  SERVICE_MATERIAL_HOW_MUCH_BUDGETS: 'service-material-how-much-budgets',
  SERVICE_MATERIAL_WHERE: 'service-material-where',
  SERVICE_MATERIAL_PAYBACK: 'service-material-payback',
  SERVICE_CONTRACT_CANCEL: 'service-contract-cancel',
  SERVICE_CONTRACT_CANCEL_DETAILS: 'service-contract-cancel-details',
  SERVICE_MATERIAL_HOW_MUCH: 'service-material-how-much',
  SERVICE_HOURS: 'service-hours',
  SERVICE_STEPS_DESCRIPTION: 'service-steps-description',
  SERVICE_HOURS_DESCRIPTION: 'service-hours-description',


};
