export const prefix = {
  DATA_PRIVACY: 'data-privacy',
  USER_FULL_NAME: 'user-full-name',
  USER_TAXPAYER_NUMBER: 'user-taxpayer-number',
  USER_PHONE_NUMBER: 'user-phone-number',
  USER_ADDRESS: 'user-address',
  USER_EMAIL: 'user-email',
  FIRST_TICKET: 'first-contract-confirmation',
  TICKET_OWNER_TYPE: 'owner-type',
  COUNTERPART_NAME: 'counterpart-name',
  COUNTERPART_TAXPAYER_NUMBER: 'counterpart-taxpayer-number',
  COUNTERPART_PHONE_NUMBER: 'counterpart-phone-number',
  COUNTERPART_EMAIL: 'counterpart-email',
  COUNTERPART_ADDRESS: 'counterpart-address',
  SERVICE_ADDRESS: 'service-address',
  SERVICE_DETAILS: 'service-details',
  SERVICE_START_DATE: 'service-start-date',
  SERVICE_END_DATE: 'service-end-date',
  SERVICE_PAYMENT_AMOUNT: 'service-payment-amount',
  SERVICE_PAYMENT_DATES: '',
  SERVICE_MATERIAL_DATE: '',
  SERVICE_MATERIAL_HOW_BUY: '',
  SERVICE_MATERIAL_HOW_MUCH_BUDGETS: '',
  SERVICE_MATERIAL_WHERE: '',
  SERVICE_MATERIAL_PAYBACK: '',
  SERVICE_CONTRACT_CANCEL: '',
  SERVICE_CONTRACT_CANCEL_DETAILS: '',
  SERVICE_MATERIAL_HOW_MUCH: '',


};
